"""Stable data contracts shared by Globex components."""

from globex_agent.domain.models import (
    CatalogRecord,
    Currency,
    DataProvenance,
    DeterministicPipelineResult,
    ItemPickerResult,
    NormalizedOffer,
    Offer,
    PickedItem,
    Platform,
    PriceCompareResult,
    PriceComparison,
    ProvenanceKind,
    RejectedItem,
    ResultStatus,
    SearchCandidate,
    SearchRequest,
    SearchResult,
    ShippingQuote,
    ShippingResult,
    ShoppingRecommendation,
    ShoppingSummaryResult,
    StandardItem,
    ToolIssue,
    UserProfile,
)

__all__ = [
    "CatalogRecord",
    "Currency",
    "DataProvenance",
    "DeterministicPipelineResult",
    "ItemPickerResult",
    "NormalizedOffer",
    "Offer",
    "PickedItem",
    "Platform",
    "PriceCompareResult",
    "PriceComparison",
    "ProvenanceKind",
    "RejectedItem",
    "ResultStatus",
    "SearchCandidate",
    "SearchRequest",
    "SearchResult",
    "ShippingQuote",
    "ShippingResult",
    "ShoppingRecommendation",
    "ShoppingSummaryResult",
    "StandardItem",
    "ToolIssue",
    "UserProfile",
]
